### ISSUE TITLE
Discoverability: Finding your course

### ISSUE THREAD

**Issue by PiotrGalusza** [illinois/queue#196]
As more courses join the Queue, it'll become harder for students to find their course. As that happens, there should probably be some sort of Departmental (CS, ECE, STAT, Misc) sorting of available courses. Alternatively, adding some sort of search functionality would be useful (type in CS, parses courses and shows only courses/queues starting with CS)

**Comment by nwalters512** [comment]
Related: #162

**Comment by rittikaadhikari** [comment]
Here's a few thoughts & a mockup that I had for increasing discoverability in the queue ~

# Increase Discoverability (Finding Course) 

## Features 
* new course page w/the ability to "star" and "unstar" a course
* "starred" courses will be at the top (for easy access to queues for course staff/those currently enrolled in class) 
* regular course cards & queues as normal @ the bottom 
* in the course page, by the name, you can "star"/"unstar" the course

## Look @ Mockup Pages in Figma
* click on CS225 under starred courses to see the updated course landing page
https://www.figma.com/file/HcUfN3MVZS8igpM0ipJdJqVE/Queue-Redesign-Landing-Page-Convenient-Lookup-Favorite-Courses?node-id=0%3A1

**Comment by rittikaadhikari** [comment]
Here are some updates after the meeting: 

I was considering adding the ability to "unpin" something from your recently viewed courses, because it would be annoying if all of your courses from last semester were still taking up space. (But I guess that wouldn't be as much of an issue, if we're only looking back a month.)

# Increase Discoverability (Finding Your Courses!) 
## Recently Viewed Queues
* stores the last ten queues visited at the top (where only marked as visited if there was some interaction -- i.e. posting question as student/answering questions as course staff)
	* closed queues are grayed out, open queues are white
* regular course cards & queues as normal at the bottom 
* makes it so that the user does not have to *constantly* search for their cues
* potentially could add a button to "unpin" a course you don't want to see in your recently viewed? (i.e. if it was for a class you took last semester, etc.)

## Mockup Page in Figma
* click on CS101 pin to "unpin" from Recently viewed queues
* https://www.figma.com/file/HcUfN3MVZS8igpM0ipJdJqVE/Queue-Redesign-Landing-Page-Convenient-Lookup-Favorite-Courses?node-id=79%3A29

**Comment by rittikaadhikari** [comment]
Resolved in #298
